CREATE SCHEMA IF NOT EXISTS ragweb;
SET search_path TO ragweb;

create sequence clients_id;

alter sequence clients_id owner to postgres;

create table clients
(
    id         integer generated by default as identity
        constraint clients_pk
            primary key,
    name       varchar not null
        constraint uniq_name
            unique,
    company    varchar not null,
    email      varchar not null
        constraint uniq_email
            unique,
    phone      varchar not null
        constraint uniq_phonr
            unique,
    code       varchar not null,
    code_used  boolean   default false,
    created_at timestamp default now(),
    updated_at timestamp default now(),
    is_premium boolean   default true,
    free_test  boolean   default true,
    expired    boolean   default false
);

alter table clients
    owner to postgres;

create table credit_card
(
    id             serial,
    completed_name varchar not null,
    number         varchar not null
        unique,
    validity       varchar not null,
    client_id      integer not null
        constraint client_id
            references clients
);

comment on table credit_card is 'Credit card client information';

alter table credit_card
    owner to postgres;

